import 'dart:convert';
import 'dart:developer';

import 'package:flutter/cupertino.dart';
import 'package:newapp/Model/states.dart';
import 'package:http/http.dart'  as http;

class StatesNamesProvider extends ChangeNotifier {
  Autogenerated states;

  Future getStates(context) async {
   var response = await http.get(Uri.parse('https://cdn-api.co-vin.in/api/v2/admin/location/states'));
   var stateResp = json.decode(response.body);

   this.states = Autogenerated.fromJson(stateResp);
    log('response data' + response.body);
   this.notifyListeners();
  }
}
